"""added email to user

Revision ID: 311efac0a784
Revises: 8555c23a3d72
Create Date: 2020-06-29 11:05:29.414240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311efac0a784'
down_revision = '8555c23a3d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
